//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhS_S_jjj
.const .align 1 .b8 .len 16 _$_str[16] = {109, 61, 37, 100, 44, 107, 61, 37, 100, 44, 110, 61, 37, 100, 10, 0};

.visible .kernel _Z12gemm16KernelPtS_S_jjj(
	.arg .ptr _Z12gemm16KernelPDhS_S_jjj_arg_0,
	.arg .ptr _Z12gemm16KernelPDhS_S_jjj_arg_1,
	.arg .ptr _Z12gemm16KernelPDhS_S_jjj_arg_2,
	.arg .s32 _Z12gemm16KernelPDhS_S_jjj_arg_3,
	.arg .s32 _Z12gemm16KernelPDhS_S_jjj_arg_4,
	.arg .s32 _Z12gemm16KernelPDhS_S_jjj_arg_5
)
{
	.gpr 	%ZERO;
	.gpr 	%r<68>;

	ld.gpr.arg 	%r30, _Z12gemm16KernelPDhS_S_jjj_arg_5, 4;
	ld.gpr.arg 	%r29, _Z12gemm16KernelPDhS_S_jjj_arg_4, 4;
	ld.gpr.arg 	%r28, _Z12gemm16KernelPDhS_S_jjj_arg_3, 4;
	lda.gpr.const 	%r31, _$_str;
	.volatile {
	//
	dumpprintf %r31, %r28, %r29, %r30;
	
	//
	}
	beq.gpr.s32 	LBB0_11, %r28, 0;
	beq.gpr.s32 	LBB0_11, %r30, 0;
	ld.gpr.arg 	%r27, _Z12gemm16KernelPDhS_S_jjj_arg_2, 6;
	ld.gpr.arg 	%r26, _Z12gemm16KernelPDhS_S_jjj_arg_1, 6;
	ld.gpr.arg 	%r25, _Z12gemm16KernelPDhS_S_jjj_arg_0, 6;
	add.gpr.ptr	%r0, %r29, 0;
	add.gpr.ptr	%r1, %r30, 0;
	add.gpr.s32 	%r58, %ZERO, 0;
	add.gpr.ptr 	%r36, %ZERO, 0x000000000000;
	add.gpr.f16 	%r37, %ZERO, 0x0000;
	mv.gpr.gpr 	%r59, %r58;
	mv.gpr.gpr 	%r60, %r58;
LBB0_3:
	bne.gpr.s32 	LBB0_4, %r29, 0;
	mv.gpr.gpr 	%r61, %r1;
	mv.gpr.gpr 	%r62, %r58;
LBB0_9:
	add.gpr.ptr	%r53, %r62, 0;
	sll.gpr.ptr 	%r54, %r53, 0x1;
	add.gpr.ptr	%r55, %r25, %r54;
	st.gdram.gpr 	[%r55], %ZERO, 2;
	add.gpr.s32 	%r62, %r62, 1;
	sub.gpr.ptr	%r61, %r61, 0x000000000001;
	ne.gpr.ptr 	%r57, %r61, 0x000000000000;
	beq.gpr.s32 	LBB0_9, %r57, 1;
	jmp 	LBB0_10;
LBB0_4:
	mul.gpr.s32 	%r5, %r60, %r30;
	mv.gpr.gpr 	%r63, %r36;
LBB0_5:
	mv.gpr.gpr 	%r15, %r63;
	mv.gpr.gpr 	%r64, %r0;
	mv.gpr.gpr 	%r65, %r15;
	mv.gpr.gpr 	%r66, %r59;
	mv.gpr.gpr 	%r67, %r37;
LBB0_6:
	add.gpr.ptr	%r38, %r66, 0;
	sll.gpr.ptr 	%r39, %r38, 0x1;
	add.gpr.ptr	%r40, %r26, %r39;
	ld.gpr.gdram 	%r41, [%r40], 2;
	add.gpr.ptr	%r42, %r65, 0;
	sll.gpr.ptr 	%r43, %r42, 0x1;
	add.gpr.ptr	%r44, %r27, %r43;
	ld.gpr.gdram 	%r45, [%r44], 2;
	mul.gpr.f16 	%r46, %r41, %r45;
	add.gpr.f16 	%r67, %r67, %r46;
	add.gpr.s32 	%r66, %r66, 1;
	add.gpr.s32 	%r65, %r65, %r30;
	sub.gpr.ptr	%r64, %r64, 0x000000000001;
	eq.gpr.ptr 	%r47, %r64, 0x000000000000;
	bne.gpr.s32 	LBB0_6, %r47, 1;
	add.gpr.s32 	%r48, %r5, %r15;
	add.gpr.ptr	%r49, %r48, 0;
	sll.gpr.ptr 	%r50, %r49, 0x1;
	add.gpr.ptr	%r51, %r25, %r50;
	st.gdram.gpr 	[%r51], %r67, 2;
	add.gpr.ptr	%r63, %r63, 0x000000000001;
	eq.gpr.ptr 	%r52, %r63, %r1;
	bne.gpr.s32 	LBB0_5, %r52, 1;
LBB0_10:
	add.gpr.s32 	%r60, %r60, 1;
	add.gpr.s32 	%r59, %r59, %r29;
	add.gpr.s32 	%r58, %r58, %r30;
	bne.gpr.s32 	LBB0_3, %r60, %r28;
LBB0_11:
	exit;
}


