//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhPaS0_jjjs
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp[65536];
.wram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM[65536];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM[131072];
.sram .align 1 .b8  .len 262144 _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM1[262144];
.sram .align 1 .b8  .len 262144 _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM2[262144];
.sram .align 32 .ptr _ZZ12gemm16KernelPDhPaS0_jjjsE15input2SRAM_read;
.sram .align 32 .ptr _ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write;

.visible .kernel _Z12gemm16KernelPtPaS0_jjjs(
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_0,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_1,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_2,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_3,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_4,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_5,
	.arg .s16 _Z12gemm16KernelPDhPaS0_jjjs_arg_6
)
{
	.gpr 	%ZERO;
	.sreg	%clusterdim, %clusterid, %coredim, %coreid, %taskdim, %taskid;
	.gpr 	%r<162>;

	ld.gpr.arg 	%r50, _Z12gemm16KernelPDhPaS0_jjjs_arg_5, 4;
	ld.gpr.arg 	%r49, _Z12gemm16KernelPDhPaS0_jjjs_arg_4, 4;
	ld.gpr.arg 	%r48, _Z12gemm16KernelPDhPaS0_jjjs_arg_3, 4;
	ld.gpr.arg 	%r47, _Z12gemm16KernelPDhPaS0_jjjs_arg_2, 6;
	ld.gpr.arg 	%r52, _Z12gemm16KernelPDhPaS0_jjjs_arg_1, 6;
	mul.gpr.s32 	%r53, %r49, %r48;
	lda.gpr.nram 	%r54, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM;
	ld.nram.gdram 	[%r54], [%r52], %r53;
	mv.gpr.sreg 	%r0, %taskdim;
	sll.gpr.u32 	%r55, %r0, 0x8;
	div.gpr.u32 	%r1, %r50, %r55;
	sll.gpr.u32 	%r56, %r49, 0x2;
	lda.gpr.sram 	%r57, _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM1;
	st.sram.gpr 	_ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write, %r57, 6;
	mv.gpr.sreg 	%r58, %clusterid;
	sll.gpr.u32 	%r5, %r49, 0xa;
	mul.gpr.s32 	%r59, %r5, %r58;
	add.gpr.ptr	%r60, %r59, 0;
	add.gpr.ptr	%r61, %r47, %r60;
	ld.sram.gdram 	[%r57], [%r61], %r5;
	mv.gpr.sreg 	%r6, %clusterdim;
	beq.gpr.s32 	LBB0_2, %r6, 0;
	mv.gpr.sreg 	%r63, %coredim;
	add.gpr.s32 	%r62, %r63, 1;
	.volatile {
	//
	barrier.sync.local 1, %r62;
	
	//
	}
LBB0_2:
	ld.gpr.arg 	%r51, _Z12gemm16KernelPDhPaS0_jjjs_arg_6, 2;
	ld.gpr.arg 	%r46, _Z12gemm16KernelPDhPaS0_jjjs_arg_0, 6;
	sll.gpr.u32 	%r2, %r49, 0x8;
	and.gpr.u32 	%r3, %r56, 0x3fffffc;
	add.gpr.s32 	%r7, %r1, -1;
	mv.gpr.sreg 	%r8, %coreid;
	add.gpr.s32 	%r64, %ZERO, 1;
	blt.gpr.s32 	LBB0_8, %r64, %r1;
	jmp 	LBB0_3;
LBB0_8:
	sll.gpr.u32 	%r4, %r58, 0x2;
	mul.gpr.s32 	%r67, %r2, %r8;
	add.gpr.ptr	%r152, %r67, 0;
	sll.gpr.u32 	%r151, %r49, 0x6;
	cvti32.gpr.tz.s16 	%r150, %r51;
	cvti48.gpr.tz.s32 	%r15, %r7;
	add.gpr.ptr	%r68, %r49, 0;
	lda.gpr.nram 	%r69, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	add.gpr.ptr	%r16, %r69, %r68;
	add.gpr.ptr	%r70, %r151, 0;
	lda.gpr.nram 	%r71, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp;
	add.gpr.ptr	%r17, %r71, %r70;
	sll.gpr.u32 	%r72, %r49, 0x1;
	add.gpr.ptr	%r73, %r72, 0;
	add.gpr.ptr	%r18, %r69, %r73;
	sll.gpr.u32 	%r74, %r49, 0x7;
	add.gpr.ptr	%r75, %r74, 0;
	add.gpr.ptr	%r19, %r71, %r75;
	mul.gpr.s32 	%r76, %r49, 3;
	add.gpr.ptr	%r77, %r76, 0;
	add.gpr.ptr	%r20, %r69, %r77;
	mul.gpr.s32 	%r78, %r49, 192;
	add.gpr.ptr	%r79, %r78, 0;
	add.gpr.ptr	%r21, %r71, %r79;
	add.gpr.ptr	%r22, %r48, 0;
	add.gpr.ptr 	%r153, %ZERO, 0x000000000000;
	lda.gpr.sram 	%r82, _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM2;
	mv.gpr.gpr 	%r112, %r15;
	mv.gpr.sreg 	%r111, %coredim;
	add.gpr.s32 	%r110, %r111, 1;
	add.gpr.s32 	%r88, %ZERO, 0;
	mv.gpr.sreg 	%r89, %taskid;
	lda.gpr.nram 	%r100, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
LBB0_9:
	mv.gpr.gpr 	%r27, %r153;
	and.gpr.u32 	%r80, %r27, 0x1;
	eq.gpr.s32 	%r81, %r80, 0;
	mv.gpr.gpr 	%r154, %r57;
	bne.gpr.s32 	LBB0_10, %r81, %ZERO;
	mv.gpr.gpr 	%r154, %r82;
LBB0_10:
	mv.gpr.gpr 	%r155, %r82;
	bne.gpr.s32 	LBB0_11, %r81, %ZERO;
	mv.gpr.gpr 	%r155, %r57;
LBB0_11:
	st.sram.gpr 	_ZZ12gemm16KernelPDhPaS0_jjjsE15input2SRAM_read, %r154, 6;
	st.sram.gpr 	_ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write, %r155, 6;
	bne.gpr.s32 	LBB0_15, %r8, 128;
	jmp 	LBB0_14;
LBB0_14:
	add.gpr.ptr	%r103, %r153, 0x000000000001;
	mv.gpr.gpr 	%r104, %r103;
	mul.gpr.s32 	%r105, %r0, %r104;
	add.gpr.s32 	%r106, %r105, %r4;
	mul.gpr.s32 	%r107, %r2, %r106;
	add.gpr.ptr	%r108, %r107, 0;
	add.gpr.ptr	%r109, %r47, %r108;
	ld.sram.gdram 	[%r155], [%r109], %r5;
	bne.gpr.s32 	LBB0_19, %r6, 0;
	jmp 	LBB0_20;
LBB0_15:
	add.gpr.ptr	%r84, %r154, %r152;
	ld.nram.sram 	_ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, [%r84], %r2;
	mv.stride.nram.nram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, %r49, %r3, %r49, 63;
	mv.stride.nram.nram	[%r16], [%r17], %r49, %r3, %r49, 63;
	mv.stride.nram.nram	[%r18], [%r19], %r49, %r3, %r49, 63;
	mv.stride.nram.nram	[%r20], [%r21], %r49, %r3, %r49, 63;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r2;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r49, %r48, 1, 1, 1, 1, 1, 256, %r150;
	beq.gpr.s32 	LBB0_18, %r48, 0;
	mul.gpr.s32 	%r30, %r0, %r27;
	mv.gpr.gpr 	%r156, %r22;
	mv.gpr.gpr 	%r157, %r88;
	mv.gpr.gpr 	%r158, %r88;
LBB0_17:
	add.gpr.s32 	%r90, %r89, %r30;
	sll.gpr.u32 	%r91, %r90, 0x8;
	cvti48.gpr.tz.s32 	%r92, %r91;
	sll.gpr.ptr 	%r93, %r92, 0x1;
	add.gpr.ptr	%r94, %r46, %r93;
	add.gpr.ptr	%r95, %r157, 0;
	sll.gpr.ptr 	%r96, %r95, 0x1;
	add.gpr.ptr	%r97, %r94, %r96;
	cvti48.gpr.tz.s32 	%r98, %r158;
	sll.gpr.ptr 	%r99, %r98, 0x1;
	add.gpr.ptr	%r101, %r100, %r99;
	st.gdram.nram 	[%r97], [%r101], 512;
	add.gpr.s32 	%r158, %r158, 256;
	add.gpr.s32 	%r157, %r157, %r50;
	sub.gpr.ptr	%r156, %r156, 0x000000000001;
	ne.gpr.ptr 	%r102, %r156, 0x000000000000;
	beq.gpr.s32 	LBB0_17, %r102, 1;
LBB0_18:
	beq.gpr.s32 	LBB0_20, %r6, 0;
LBB0_19:
	.volatile {
	//
	barrier.sync.local 1, %r110;
	
	//
	}
LBB0_20:
	add.gpr.ptr	%r153, %r153, 0x000000000001;
	mv.gpr.gpr 	%r113, %r153;
	blt.gpr.s32 	LBB0_9, %r113, %r112;
	jmp 	LBB0_4;
LBB0_3:
	mul.gpr.s32 	%r65, %r2, %r8;
	add.gpr.ptr	%r152, %r65, 0;
	sll.gpr.u32 	%r151, %r49, 0x6;
	cvti32.gpr.tz.s16 	%r150, %r51;
LBB0_4:
	ld.gpr.sram 	%r114, _ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write, 6;
	add.gpr.ptr	%r115, %r114, %r152;
	lda.gpr.nram 	%r116, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp;
	ld.nram.sram 	_ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, [%r115], %r2;
	lda.gpr.nram 	%r117, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	mv.stride.nram.nram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, %r49, %r3, %r49, 63;
	add.gpr.ptr	%r118, %r49, 0;
	add.gpr.ptr	%r119, %r117, %r118;
	add.gpr.ptr	%r120, %r151, 0;
	add.gpr.ptr	%r121, %r116, %r120;
	mv.stride.nram.nram	[%r119], [%r121], %r49, %r3, %r49, 63;
	sll.gpr.u32 	%r122, %r49, 0x1;
	add.gpr.ptr	%r123, %r122, 0;
	add.gpr.ptr	%r124, %r117, %r123;
	sll.gpr.u32 	%r125, %r151, 0x1;
	add.gpr.ptr	%r126, %r125, 0;
	add.gpr.ptr	%r127, %r116, %r126;
	mv.stride.nram.nram	[%r124], [%r127], %r49, %r3, %r49, 63;
	mul.gpr.s32 	%r128, %r49, 3;
	add.gpr.ptr	%r129, %r128, 0;
	add.gpr.ptr	%r130, %r117, %r129;
	mul.gpr.s32 	%r131, %r151, 3;
	add.gpr.ptr	%r132, %r131, 0;
	add.gpr.ptr	%r133, %r116, %r132;
	mv.stride.nram.nram	[%r130], [%r133], %r49, %r3, %r49, 63;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r2;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r49, %r48, 1, 1, 1, 1, 1, 256, %r150;
	beq.gpr.s32 	LBB0_7, %r48, 0;
	mul.gpr.s32 	%r38, %r7, %r0;
	add.gpr.ptr	%r159, %r48, 0;
	add.gpr.s32 	%r160, %ZERO, 0;
	mv.gpr.sreg 	%r136, %taskid;
	add.gpr.s32 	%r137, %r136, %r38;
	sll.gpr.u32 	%r138, %r137, 0x8;
	cvti48.gpr.tz.s32 	%r139, %r138;
	sll.gpr.ptr 	%r140, %r139, 0x1;
	add.gpr.ptr	%r141, %r46, %r140;
	lda.gpr.nram 	%r147, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
	mv.gpr.gpr 	%r161, %r160;
LBB0_6:
	add.gpr.ptr	%r142, %r160, 0;
	sll.gpr.ptr 	%r143, %r142, 0x1;
	add.gpr.ptr	%r144, %r141, %r143;
	cvti48.gpr.tz.s32 	%r145, %r161;
	sll.gpr.ptr 	%r146, %r145, 0x1;
	add.gpr.ptr	%r148, %r147, %r146;
	st.gdram.nram 	[%r144], [%r148], 512;
	add.gpr.s32 	%r161, %r161, 256;
	add.gpr.s32 	%r160, %r160, %r50;
	sub.gpr.ptr	%r159, %r159, 0x000000000001;
	eq.gpr.ptr 	%r149, %r159, 0x000000000000;
	bne.gpr.s32 	LBB0_6, %r149, 1;
LBB0_7:
	exit;
}


