//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhPaS0_jjjs
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE4temp[65536];
.wram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM[65536];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM[131072];

.visible .kernel _Z12gemm16KernelPtPaS0_jjjs(
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_0,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_1,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_2,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_3,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_4,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_5,
	.arg .s16 _Z12gemm16KernelPDhPaS0_jjjs_arg_6
)
{
	.gpr 	%ZERO;
	.sreg	%taskdim, %taskid;
	.gpr 	%r<211>;

	ld.gpr.arg 	%r74, _Z12gemm16KernelPDhPaS0_jjjs_arg_6, 2;
	ld.gpr.arg 	%r73, _Z12gemm16KernelPDhPaS0_jjjs_arg_5, 4;
	ld.gpr.arg 	%r72, _Z12gemm16KernelPDhPaS0_jjjs_arg_4, 4;
	ld.gpr.arg 	%r71, _Z12gemm16KernelPDhPaS0_jjjs_arg_3, 4;
	ld.gpr.arg 	%r70, _Z12gemm16KernelPDhPaS0_jjjs_arg_2, 6;
	ld.gpr.arg 	%r69, _Z12gemm16KernelPDhPaS0_jjjs_arg_0, 6;
	ld.gpr.arg 	%r75, _Z12gemm16KernelPDhPaS0_jjjs_arg_1, 6;
	and.gpr.u32 	%r76, %r72, 0x7f;
	ne.gpr.s32 	%r77, %r76, 0;
	sll.gpr.u32 	%r78, %r77, 0x7;
	add.gpr.s32 	%r79, %r78, %r72;
	and.gpr.u32 	%r0, %r79, 0xffffff80;
	div.gpr.u32 	%r80, 0x10000, %r0;
	srl.gpr.u32 	%r1, %r80, 0x6;
	and.gpr.u32 	%r2, %r80, 0x1ffc0;
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, 32768;
	add.gpr.s32 	%r82, %r71, -1;
	ld.stride.nram.gdram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, [%r75], %r72, %r0, %r72, %r82;
	div.gpr.u32 	%r83, %r73, %r2;
	rem.gpr.u32 	%r204, %r73, %r2;
	ne.gpr.s32 	%r84, %r204, 0;
	add.gpr.s32 	%r85, %r83, %r84;
	mv.gpr.sreg 	%r4, %taskdim;
	div.gpr.s32 	%r5, %r85, %r4;
	rem.gpr.s32 	%r6, %r85, %r4;
	mul.gpr.s32 	%r7, %r2, %r0;
	srl.gpr.u32 	%r8, %r7, 0x6;
	blt.gpr.s32 	LBB0_2, %ZERO, %r5;
	jmp 	LBB0_1;
LBB0_2:
	add.gpr.s32 	%r10, %r2, -1;
	cvti32.gpr.tz.s16 	%r11, %r74;
	sll.gpr.u32 	%r12, %r2, 0x1;
	bne.gpr.s32 	LBB0_3, %r1, 0;
	beq.gpr.s32 	LBB0_11, %r71, 0;
	add.gpr.ptr	%r33, %r71, 0;
	add.gpr.s32 	%r128, %ZERO, 0;
	mv.gpr.sreg 	%r200, %taskid;
	add.gpr.ptr 	%r130, %ZERO, 0x000000000000;
	lda.gpr.nram 	%r149, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
	mv.gpr.gpr 	%r196, %r128;
LBB0_14:
	mul.gpr.s32 	%r131, %r196, %r4;
	add.gpr.s32 	%r132, %r200, %r131;
	mul.gpr.s32 	%r133, %r132, %r2;
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, 32768;
	mul.gpr.s32 	%r135, %r133, %r72;
	add.gpr.ptr	%r136, %r135, 0;
	add.gpr.ptr	%r137, %r70, %r136;
	ld.stride.nram.gdram	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, [%r137], %r72, %r0, %r72, %r10;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r7;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r0, %r71, 1, 1, 1, 1, 1, %r2, %r11;
	cvti48.gpr.tz.s32 	%r140, %r133;
	sll.gpr.ptr 	%r141, %r140, 0x1;
	add.gpr.ptr	%r36, %r69, %r141;
	mv.gpr.gpr 	%r197, %r33;
	mv.gpr.gpr 	%r198, %r128;
	mv.gpr.gpr 	%r199, %r130;
LBB0_15:
	mv.gpr.gpr 	%r142, %r199;
	add.gpr.ptr	%r143, %r198, 0;
	sll.gpr.ptr 	%r144, %r143, 0x1;
	add.gpr.ptr	%r145, %r36, %r144;
	mul.gpr.s32 	%r146, %r2, %r142;
	add.gpr.ptr	%r147, %r146, 0;
	sll.gpr.ptr 	%r148, %r147, 0x1;
	add.gpr.ptr	%r150, %r149, %r148;
	st.gdram.nram 	[%r145], [%r150], %r12;
	add.gpr.ptr	%r199, %r199, 0x000000000001;
	add.gpr.s32 	%r198, %r198, %r73;
	sub.gpr.ptr	%r197, %r197, 0x000000000001;
	ne.gpr.ptr 	%r151, %r197, 0x000000000000;
	beq.gpr.s32 	LBB0_15, %r151, 1;
	add.gpr.s32 	%r196, %r196, 1;
	bne.gpr.s32 	LBB0_14, %r196, %r5;
	jmp 	LBB0_17;
LBB0_1:
	mv.gpr.sreg 	%r200, %taskid;
	blt.gpr.s32 	LBB0_18, %r200, %r6;
	jmp 	LBB0_26;
LBB0_3:
	sll.gpr.u32 	%r13, %r0, 0x6;
	add.gpr.ptr	%r14, %r1, 0;
	add.gpr.ptr	%r15, %r71, 0;
	add.gpr.s32 	%r87, %ZERO, 0;
	mv.gpr.sreg 	%r200, %taskid;
	lda.gpr.nram 	%r92, _ZZ12gemm16KernelPDhPaS0_jjjsE4temp;
	add.gpr.ptr 	%r89, %ZERO, 0x000000000000;
	lda.gpr.nram 	%r97, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	lda.gpr.nram 	%r116, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
	mv.gpr.gpr 	%r189, %r87;
LBB0_4:
	mul.gpr.s32 	%r90, %r189, %r4;
	add.gpr.s32 	%r91, %r200, %r90;
	mul.gpr.s32 	%r18, %r91, %r2;
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, 32768;
	mul.gpr.s32 	%r93, %r18, %r72;
	add.gpr.ptr	%r94, %r93, 0;
	add.gpr.ptr	%r95, %r70, %r94;
	ld.stride.nram.gdram	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, [%r95], %r72, %r0, %r72, %r10;
	mv.gpr.gpr 	%r193, %r87;
	mv.gpr.gpr 	%r194, %r87;
	mv.gpr.gpr 	%r195, %r89;
LBB0_5:
	add.gpr.ptr	%r96, %r194, 0;
	add.gpr.ptr	%r98, %r97, %r96;
	add.gpr.ptr	%r99, %r193, 0;
	add.gpr.ptr	%r101, %r92, %r99;
	mv.stride.nram.nram	[%r98], [%r101], %r0, %r8, %r0, 63;
	add.gpr.ptr	%r195, %r195, 0x000000000001;
	add.gpr.s32 	%r194, %r194, %r0;
	add.gpr.s32 	%r193, %r193, %r13;
	ne.gpr.ptr 	%r102, %r195, %r14;
	beq.gpr.s32 	LBB0_5, %r102, 1;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r7;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r0, %r71, 1, 1, 1, 1, 1, %r2, %r11;
	beq.gpr.s32 	LBB0_9, %r71, 0;
	cvti48.gpr.tz.s32 	%r107, %r18;
	sll.gpr.ptr 	%r108, %r107, 0x1;
	add.gpr.ptr	%r32, %r69, %r108;
	mv.gpr.gpr 	%r190, %r15;
	mv.gpr.gpr 	%r191, %r87;
	mv.gpr.gpr 	%r192, %r89;
LBB0_8:
	mv.gpr.gpr 	%r109, %r192;
	add.gpr.ptr	%r110, %r191, 0;
	sll.gpr.ptr 	%r111, %r110, 0x1;
	add.gpr.ptr	%r112, %r32, %r111;
	mul.gpr.s32 	%r113, %r2, %r109;
	add.gpr.ptr	%r114, %r113, 0;
	sll.gpr.ptr 	%r115, %r114, 0x1;
	add.gpr.ptr	%r117, %r116, %r115;
	st.gdram.nram 	[%r112], [%r117], %r12;
	add.gpr.ptr	%r192, %r192, 0x000000000001;
	add.gpr.s32 	%r191, %r191, %r73;
	sub.gpr.ptr	%r190, %r190, 0x000000000001;
	eq.gpr.ptr 	%r118, %r190, 0x000000000000;
	bne.gpr.s32 	LBB0_8, %r118, 1;
LBB0_9:
	add.gpr.s32 	%r189, %r189, 1;
	bne.gpr.s32 	LBB0_4, %r189, %r5;
	jmp 	LBB0_17;
LBB0_11:
	add.gpr.s32 	%r201, %ZERO, 0;
	mv.gpr.sreg 	%r200, %taskid;
	mv.gpr.gpr 	%r202, %r5;
LBB0_12:
	add.gpr.s32 	%r120, %r200, %r201;
	mul.gpr.s32 	%r121, %r120, %r2;
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, 32768;
	mul.gpr.s32 	%r123, %r121, %r72;
	add.gpr.ptr	%r124, %r123, 0;
	add.gpr.ptr	%r125, %r70, %r124;
	ld.stride.nram.gdram	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, [%r125], %r72, %r0, %r72, %r10;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r7;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r0, 0, 1, 1, 1, 1, 1, %r2, %r11;
	add.gpr.s32 	%r202, %r202, -1;
	add.gpr.s32 	%r201, %r201, %r4;
	bne.gpr.s32 	LBB0_12, %r202, 0;
LBB0_17:
	blt.gpr.s32 	LBB0_18, %r200, %r6;
	jmp 	LBB0_26;
LBB0_18:
	mul.gpr.s32 	%r153, %r5, %r4;
	add.gpr.s32 	%r154, %r200, %r153;
	add.gpr.s32 	%r155, %r6, -1;
	beq.gpr.s32 	LBB0_19, %r200, %r155;
	mv.gpr.gpr 	%r204, %r2;
LBB0_19:
	mul.gpr.s32 	%r50, %r154, %r2;
	bne.gpr.s32 	LBB0_20, %r84, %ZERO;
	mv.gpr.gpr 	%r204, %r2;
LBB0_20:
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, 32768;
	lda.gpr.nram 	%r158, _ZZ12gemm16KernelPDhPaS0_jjjsE4temp;
	mul.gpr.s32 	%r159, %r50, %r72;
	add.gpr.ptr	%r160, %r159, 0;
	add.gpr.ptr	%r161, %r70, %r160;
	add.gpr.s32 	%r162, %r204, -1;
	ld.stride.nram.gdram	_ZZ12gemm16KernelPDhPaS0_jjjsE4temp, [%r161], %r72, %r0, %r72, %r162;
	beq.gpr.s32 	LBB0_23, %r1, 0;
	jmp 	LBB0_27;
LBB0_27:
	sll.gpr.u32 	%r52, %r0, 0x6;
	add.gpr.ptr	%r53, %r1, 0;
	add.gpr.ptr 	%r207, %ZERO, 0x000000000000;
	add.gpr.s32 	%r205, %ZERO, 0;
	lda.gpr.nram 	%r166, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	mv.gpr.gpr 	%r206, %r205;
LBB0_28:
	add.gpr.ptr	%r165, %r206, 0;
	add.gpr.ptr	%r167, %r166, %r165;
	add.gpr.ptr	%r168, %r205, 0;
	add.gpr.ptr	%r170, %r158, %r168;
	mv.stride.nram.nram	[%r167], [%r170], %r0, %r8, %r0, 63;
	add.gpr.ptr	%r207, %r207, 0x000000000001;
	add.gpr.s32 	%r206, %r206, %r0;
	add.gpr.s32 	%r205, %r205, %r52;
	eq.gpr.ptr 	%r171, %r207, %r53;
	bne.gpr.s32 	LBB0_28, %r171, 1;
LBB0_23:
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r7;
	cvti32.gpr.tz.s16 	%r174, %r74;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r0, %r71, 1, 1, 1, 1, 1, %r2, %r174;
	beq.gpr.s32 	LBB0_26, %r71, 0;
	cvti48.gpr.tz.s32 	%r177, %r50;
	sll.gpr.ptr 	%r178, %r177, 0x1;
	add.gpr.ptr	%r54, %r69, %r178;
	sll.gpr.u32 	%r55, %r204, 0x1;
	add.gpr.ptr	%r208, %r71, 0;
	add.gpr.ptr 	%r210, %ZERO, 0x000000000000;
	add.gpr.s32 	%r209, %ZERO, 0;
	lda.gpr.nram 	%r186, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
LBB0_25:
	mv.gpr.gpr 	%r179, %r210;
	add.gpr.ptr	%r180, %r209, 0;
	sll.gpr.ptr 	%r181, %r180, 0x1;
	add.gpr.ptr	%r182, %r54, %r181;
	mul.gpr.s32 	%r183, %r2, %r179;
	add.gpr.ptr	%r184, %r183, 0;
	sll.gpr.ptr 	%r185, %r184, 0x1;
	add.gpr.ptr	%r187, %r186, %r185;
	st.gdram.nram 	[%r182], [%r187], %r55;
	add.gpr.ptr	%r210, %r210, 0x000000000001;
	add.gpr.s32 	%r209, %r209, %r73;
	sub.gpr.ptr	%r208, %r208, 0x000000000001;
	ne.gpr.ptr 	%r188, %r208, 0x000000000000;
	beq.gpr.s32 	LBB0_25, %r188, 1;
LBB0_26:
	exit;
}


