//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhPaS0_jjjs
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp[65536];
.wram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM[65536];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM[131072];

.visible .kernel _Z12gemm16KernelPtPaS0_jjjs(
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_0,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_1,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_2,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_3,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_4,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_5,
	.arg .s16 _Z12gemm16KernelPDhPaS0_jjjs_arg_6
)
{
	.gpr 	%ZERO;
	.sreg	%taskdim, %taskid;
	.gpr 	%r<87>;

	ld.gpr.arg 	%r29, _Z12gemm16KernelPDhPaS0_jjjs_arg_5, 4;
	ld.gpr.arg 	%r28, _Z12gemm16KernelPDhPaS0_jjjs_arg_4, 4;
	ld.gpr.arg 	%r27, _Z12gemm16KernelPDhPaS0_jjjs_arg_3, 4;
	ld.gpr.arg 	%r31, _Z12gemm16KernelPDhPaS0_jjjs_arg_1, 6;
	mul.gpr.s32 	%r32, %r28, %r27;
	lda.gpr.nram 	%r33, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM;
	ld.nram.gdram 	[%r33], [%r31], %r32;
	mv.gpr.sreg 	%r0, %taskdim;
	sll.gpr.u32 	%r34, %r0, 0x8;
	div.gpr.u32 	%r1, %r29, %r34;
	blt.gpr.s32 	LBB0_8, %r1, 1;
	ld.gpr.arg 	%r30, _Z12gemm16KernelPDhPaS0_jjjs_arg_6, 2;
	ld.gpr.arg 	%r26, _Z12gemm16KernelPDhPaS0_jjjs_arg_2, 6;
	sll.gpr.u32 	%r2, %r28, 0x8;
	sll.gpr.u32 	%r35, %r28, 0x2;
	and.gpr.u32 	%r3, %r35, 0x3fffffc;
	sll.gpr.u32 	%r36, %r28, 0x6;
	cvti32.gpr.tz.s16 	%r4, %r30;
	add.gpr.ptr	%r37, %r28, 0;
	lda.gpr.nram 	%r38, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	add.gpr.ptr	%r5, %r38, %r37;
	add.gpr.ptr	%r39, %r36, 0;
	lda.gpr.nram 	%r40, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp;
	add.gpr.ptr	%r6, %r40, %r39;
	sll.gpr.u32 	%r41, %r28, 0x1;
	add.gpr.ptr	%r42, %r41, 0;
	add.gpr.ptr	%r7, %r38, %r42;
	sll.gpr.u32 	%r43, %r28, 0x7;
	add.gpr.ptr	%r44, %r43, 0;
	add.gpr.ptr	%r8, %r40, %r44;
	mul.gpr.s32 	%r45, %r28, 3;
	add.gpr.ptr	%r46, %r45, 0;
	add.gpr.ptr	%r9, %r38, %r46;
	mul.gpr.s32 	%r47, %r28, 192;
	add.gpr.ptr	%r48, %r47, 0;
	add.gpr.ptr	%r10, %r40, %r48;
	bne.gpr.s32 	LBB0_4, %r27, 0;
	add.gpr.s32 	%r85, %ZERO, 0;
	mv.gpr.sreg 	%r72, %taskid;
	mv.gpr.gpr 	%r86, %r85;
LBB0_3:
	add.gpr.s32 	%r73, %r72, %r85;
	mul.gpr.s32 	%r74, %r73, %r28;
	sll.gpr.u32 	%r75, %r74, 0x8;
	add.gpr.ptr	%r76, %r75, 0;
	add.gpr.ptr	%r77, %r26, %r76;
	ld.nram.gdram 	[%r40], [%r77], %r2;
	mv.stride.nram.nram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, %r28, %r3, %r28, 63;
	mv.stride.nram.nram	[%r5], [%r6], %r28, %r3, %r28, 63;
	mv.stride.nram.nram	[%r7], [%r8], %r28, %r3, %r28, 63;
	mv.stride.nram.nram	[%r9], [%r10], %r28, %r3, %r28, 63;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r2;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r28, 0, 1, 1, 1, 1, 1, 256, %r4;
	add.gpr.s32 	%r86, %r86, 1;
	add.gpr.s32 	%r85, %r85, %r0;
	blt.gpr.s32 	LBB0_3, %r86, %r1;
	jmp 	LBB0_8;
LBB0_4:
	ld.gpr.arg 	%r25, _Z12gemm16KernelPDhPaS0_jjjs_arg_0, 6;
	add.gpr.ptr	%r11, %r27, 0;
	add.gpr.s32 	%r49, %ZERO, 0;
	mv.gpr.sreg 	%r52, %taskid;
	lda.gpr.nram 	%r68, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
	mv.gpr.gpr 	%r81, %r49;
LBB0_5:
	mul.gpr.s32 	%r51, %r81, %r0;
	add.gpr.s32 	%r53, %r52, %r51;
	sll.gpr.u32 	%r54, %r53, 0x8;
	mul.gpr.s32 	%r55, %r54, %r28;
	add.gpr.ptr	%r56, %r55, 0;
	add.gpr.ptr	%r57, %r26, %r56;
	ld.nram.gdram 	[%r40], [%r57], %r2;
	mv.stride.nram.nram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, %r28, %r3, %r28, 63;
	mv.stride.nram.nram	[%r5], [%r6], %r28, %r3, %r28, 63;
	mv.stride.nram.nram	[%r7], [%r8], %r28, %r3, %r28, 63;
	mv.stride.nram.nram	[%r9], [%r10], %r28, %r3, %r28, 63;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r2;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r28, %r27, 1, 1, 1, 1, 1, 256, %r4;
	cvti48.gpr.tz.s32 	%r61, %r54;
	sll.gpr.ptr 	%r62, %r61, 0x1;
	add.gpr.ptr	%r13, %r25, %r62;
	mv.gpr.gpr 	%r82, %r11;
	mv.gpr.gpr 	%r83, %r49;
	mv.gpr.gpr 	%r84, %r49;
LBB0_6:
	add.gpr.ptr	%r63, %r83, 0;
	sll.gpr.ptr 	%r64, %r63, 0x1;
	add.gpr.ptr	%r65, %r13, %r64;
	cvti48.gpr.tz.s32 	%r66, %r84;
	sll.gpr.ptr 	%r67, %r66, 0x1;
	add.gpr.ptr	%r69, %r68, %r67;
	st.gdram.nram 	[%r65], [%r69], 512;
	add.gpr.s32 	%r84, %r84, 256;
	add.gpr.s32 	%r83, %r83, %r29;
	sub.gpr.ptr	%r82, %r82, 0x000000000001;
	ne.gpr.ptr 	%r70, %r82, 0x000000000000;
	beq.gpr.s32 	LBB0_6, %r70, 1;
	add.gpr.s32 	%r81, %r81, 1;
	blt.gpr.s32 	LBB0_5, %r81, %r1;
LBB0_8:
	exit;
}


