//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhS_S_jjj
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhS_S_jjjE10input1NRAM[131072];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhS_S_jjjE10input2NRAM[131072];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhS_S_jjjE10outputNRAM[131072];

.visible .kernel _Z12gemm16KernelPtS_S_jjj(
	.arg .ptr _Z12gemm16KernelPDhS_S_jjj_arg_0,
	.arg .ptr _Z12gemm16KernelPDhS_S_jjj_arg_1,
	.arg .ptr _Z12gemm16KernelPDhS_S_jjj_arg_2,
	.arg .s32 _Z12gemm16KernelPDhS_S_jjj_arg_3,
	.arg .s32 _Z12gemm16KernelPDhS_S_jjj_arg_4,
	.arg .s32 _Z12gemm16KernelPDhS_S_jjj_arg_5
)
{
	.gpr 	%ZERO;
	.gpr 	%r<81>;

	ld.gpr.arg 	%r31, _Z12gemm16KernelPDhS_S_jjj_arg_5, 4;
	ld.gpr.arg 	%r30, _Z12gemm16KernelPDhS_S_jjj_arg_4, 4;
	ld.gpr.arg 	%r29, _Z12gemm16KernelPDhS_S_jjj_arg_3, 4;
	ld.gpr.arg 	%r28, _Z12gemm16KernelPDhS_S_jjj_arg_0, 6;
	ld.gpr.arg 	%r32, _Z12gemm16KernelPDhS_S_jjj_arg_1, 6;
	ld.gpr.arg 	%r33, _Z12gemm16KernelPDhS_S_jjj_arg_2, 6;
	sll.gpr.u32 	%r0, %r29, 0x1;
	mul.gpr.s32 	%r34, %r0, %r30;
	lda.gpr.nram 	%r35, _ZZ12gemm16KernelPDhS_S_jjjE10input1NRAM;
	ld.nram.gdram 	[%r35], [%r32], %r34;
	mul.gpr.s32 	%r36, %r30, %r31;
	sll.gpr.u32 	%r37, %r36, 0x1;
	lda.gpr.nram 	%r38, _ZZ12gemm16KernelPDhS_S_jjjE10input2NRAM;
	ld.nram.gdram 	[%r38], [%r33], %r37;
	beq.gpr.s32 	LBB0_11, %r29, 0;
	beq.gpr.s32 	LBB0_11, %r31, 0;
	add.gpr.ptr	%r1, %r30, 0;
	add.gpr.ptr	%r2, %r31, 0;
	add.gpr.s32 	%r70, %ZERO, 0;
	lda.gpr.nram 	%r64, _ZZ12gemm16KernelPDhS_S_jjjE10outputNRAM;
	add.gpr.ptr 	%r40, %ZERO, 0x000000000000;
	add.gpr.f16 	%r41, %ZERO, 0x0000;
	mv.gpr.gpr 	%r71, %r70;
	mv.gpr.gpr 	%r72, %r70;
LBB0_3:
	bne.gpr.s32 	LBB0_4, %r30, 0;
	mv.gpr.gpr 	%r73, %r2;
	mv.gpr.gpr 	%r74, %r70;
LBB0_9:
	add.gpr.ptr	%r62, %r74, 0;
	sll.gpr.ptr 	%r63, %r62, 0x1;
	add.gpr.ptr	%r65, %r64, %r63;
	st.nram.gpr 	[%r65], %ZERO, 2;
	add.gpr.s32 	%r74, %r74, 1;
	sub.gpr.ptr	%r73, %r73, 0x000000000001;
	ne.gpr.ptr 	%r67, %r73, 0x000000000000;
	beq.gpr.s32 	LBB0_9, %r67, 1;
	jmp 	LBB0_10;
LBB0_4:
	mul.gpr.s32 	%r6, %r72, %r31;
	mv.gpr.gpr 	%r75, %r40;
LBB0_5:
	mv.gpr.gpr 	%r16, %r75;
	mv.gpr.gpr 	%r76, %r1;
	mv.gpr.gpr 	%r77, %r16;
	mv.gpr.gpr 	%r78, %r71;
	mv.gpr.gpr 	%r79, %r41;
	mv.gpr.gpr 	%r80, %r41;
LBB0_6:
	add.gpr.ptr	%r42, %r78, 0;
	sll.gpr.ptr 	%r43, %r42, 0x1;
	add.gpr.ptr	%r45, %r35, %r43;
	ld.gpr.nram 	%r46, [%r45], 2;
	add.gpr.ptr	%r47, %r77, 0;
	sll.gpr.ptr 	%r48, %r47, 0x1;
	add.gpr.ptr	%r50, %r38, %r48;
	ld.gpr.nram 	%r51, [%r50], 2;
	mul.gpr.f16 	%r52, %r46, %r51;
	sub.gpr.f16 	%r53, %r52, %r79;
	add.gpr.f16 	%r23, %r80, %r53;
	sub.gpr.f16 	%r54, %r23, %r80;
	sub.gpr.f16 	%r79, %r54, %r53;
	add.gpr.s32 	%r78, %r78, 1;
	add.gpr.s32 	%r77, %r77, %r31;
	sub.gpr.ptr	%r76, %r76, 0x000000000001;
	eq.gpr.ptr 	%r55, %r76, 0x000000000000;
	mv.gpr.gpr 	%r80, %r23;
	bne.gpr.s32 	LBB0_6, %r55, 1;
	add.gpr.s32 	%r56, %r6, %r16;
	add.gpr.ptr	%r57, %r56, 0;
	sll.gpr.ptr 	%r58, %r57, 0x1;
	add.gpr.ptr	%r60, %r64, %r58;
	st.nram.gpr 	[%r60], %r23, 2;
	add.gpr.ptr	%r75, %r75, 0x000000000001;
	eq.gpr.ptr 	%r61, %r75, %r2;
	bne.gpr.s32 	LBB0_5, %r61, 1;
LBB0_10:
	add.gpr.s32 	%r72, %r72, 1;
	add.gpr.s32 	%r71, %r71, %r30;
	add.gpr.s32 	%r70, %r70, %r31;
	bne.gpr.s32 	LBB0_3, %r72, %r29;
LBB0_11:
	mul.gpr.s32 	%r68, %r0, %r31;
	lda.gpr.nram 	%r69, _ZZ12gemm16KernelPDhS_S_jjjE10outputNRAM;
	st.gdram.nram 	[%r28], [%r69], %r68;
	exit;
}


