//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhPaS0_jjjs
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp[65536];
.wram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM[65536];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM[131072];

.visible .kernel _Z12gemm16KernelPtPaS0_jjjs(
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_0,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_1,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_2,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_3,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_4,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_5,
	.arg .s16 _Z12gemm16KernelPDhPaS0_jjjs_arg_6
)
{
	.gpr 	%ZERO;
	.gpr 	%r<57>;

	ld.gpr.arg 	%r24, _Z12gemm16KernelPDhPaS0_jjjs_arg_5, 4;
	ld.gpr.arg 	%r23, _Z12gemm16KernelPDhPaS0_jjjs_arg_4, 4;
	ld.gpr.arg 	%r22, _Z12gemm16KernelPDhPaS0_jjjs_arg_3, 4;
	ld.gpr.arg 	%r26, _Z12gemm16KernelPDhPaS0_jjjs_arg_1, 6;
	mul.gpr.s32 	%r27, %r23, %r22;
	lda.gpr.nram 	%r28, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM;
	ld.nram.gdram 	[%r28], [%r26], %r27;
	srl.gpr.u32 	%r0, %r24, 0x8;
	beq.gpr.s32 	LBB0_3, %r0, 0;
	ld.gpr.arg 	%r25, _Z12gemm16KernelPDhPaS0_jjjs_arg_6, 2;
	ld.gpr.arg 	%r21, _Z12gemm16KernelPDhPaS0_jjjs_arg_2, 6;
	ld.gpr.arg 	%r20, _Z12gemm16KernelPDhPaS0_jjjs_arg_0, 6;
	sll.gpr.u32 	%r1, %r23, 0x8;
	sll.gpr.u32 	%r29, %r23, 0x2;
	and.gpr.u32 	%r2, %r29, 0x3fffffc;
	sll.gpr.u32 	%r31, %r23, 0x6;
	cvti32.gpr.tz.s16 	%r3, %r25;
	sll.gpr.u32 	%r4, %r24, 0x1;
	add.gpr.s32 	%r5, %r22, -1;
	add.gpr.ptr	%r32, %r23, 0;
	lda.gpr.nram 	%r33, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	add.gpr.ptr	%r6, %r33, %r32;
	add.gpr.ptr	%r34, %r31, 0;
	lda.gpr.nram 	%r35, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp;
	add.gpr.ptr	%r7, %r35, %r34;
	sll.gpr.u32 	%r36, %r23, 0x1;
	add.gpr.ptr	%r37, %r36, 0;
	add.gpr.ptr	%r8, %r33, %r37;
	sll.gpr.u32 	%r38, %r23, 0x7;
	add.gpr.ptr	%r39, %r38, 0;
	add.gpr.ptr	%r9, %r35, %r39;
	mul.gpr.s32 	%r40, %r23, 3;
	add.gpr.ptr	%r41, %r40, 0;
	add.gpr.ptr	%r10, %r33, %r41;
	mul.gpr.s32 	%r42, %r23, 192;
	add.gpr.ptr	%r43, %r42, 0;
	add.gpr.ptr	%r11, %r35, %r43;
	add.gpr.ptr	%r54, %r0, 0;
	add.gpr.s32 	%r55, %ZERO, 0;
	lda.gpr.nram 	%r49, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
	mv.gpr.gpr 	%r56, %r55;
LBB0_2:
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, 32768;
	writezero.nram.f16	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, 32768;
	add.gpr.ptr	%r46, %r56, 0;
	add.gpr.ptr	%r47, %r21, %r46;
	ld.nram.gdram 	[%r35], [%r47], %r1;
	mv.stride.nram.nram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, %r23, %r2, %r23, 63;
	mv.stride.nram.nram	[%r6], [%r7], %r23, %r2, %r23, 63;
	mv.stride.nram.nram	[%r8], [%r9], %r23, %r2, %r23, 63;
	mv.stride.nram.nram	[%r10], [%r11], %r23, %r2, %r23, 63;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r1;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r23, %r22, 1, 1, 1, 1, 1, 256, %r3;
	cvti48.gpr.tz.s32 	%r50, %r55;
	sll.gpr.ptr 	%r51, %r50, 0x1;
	add.gpr.ptr	%r52, %r20, %r51;
	st.stride.gdram.nram	[%r52], [%r49], 512, %r4, 512, %r5;
	add.gpr.s32 	%r56, %r56, %r1;
	add.gpr.s32 	%r55, %r55, 256;
	sub.gpr.ptr	%r54, %r54, 0x000000000001;
	eq.gpr.ptr 	%r53, %r54, 0x000000000000;
	bne.gpr.s32 	LBB0_2, %r53, 1;
LBB0_3:
	exit;
}


